### ISSUE TITLE
Great Project..   Have a question.

### ISSUE THREAD

**Issue by casp2277** [AdventCoding/Timespace#1]
Great Project....    Attempting to use it to timeline work histories by building a map of their resume. 
I have been trying to modify the width of the TimespaceEvent, but I have been unable to figure out how to modify the minimum width (In my situation, it looks like jobs are overlapping).   I need the default width of the event <p> to be closer to the <span> size.   I have tried to modify (about every constant in the js file and every setting in the css) but there is still significant padding on the right of the text inside of the event.    

Any suggestions or help would be greatly appreciated.     cpratt@hpcenters.com

**Comment by AdventCoding** [comment]
The most recent issue has altered the event box width. The way it chooses the width is:
1st: If the event box extends past the timeline container, it uses the event's text span width
2nd: If a 'width' is supplied on the event object in the events array that is passed into the plugin
3rd: If the text span width is greater than the time span width (e.g. 1900 to 2000) AND markerWidth option
4th: If the time span width is greater than the markerWidth option
last: The markerWidth option

Can you take a screenshot with the newest version in use? What size are you wanting the default width of the event to be?
Thanks.
